id: '0444_00_400'
modifiers: _scaled_normalized_transformed
original_path: '/igd/a4/homestud/pejiang/scenes/multi/0444_00/0444_00_400.pth'
base_path: '/igd/a4/homestud/pejiang/scenes/multi/0444_00/'
ply: '/igd/a4/homestud/pejiang/scenes/multi/0444_00/0444_00_400_scaled_normalized_transformed.ply'
