id: scene0444_00_vh_clean_2
modifiers: '_normalized'
original_path: '/igd/a4/homestud/pejiang/ScanNet/scans/scene0444_00/scene0444_00_vh_clean_2.ply'
base_path: '/igd/a4/homestud/pejiang/ScanNet/scans/scene0444_00/'
ply: '/igd/a4/homestud/pejiang/ScanNet/scans/scene0444_00/scene0444_00_vh_clean_2.ply'
